---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизоваться на сайте
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность присоединиться к игре
  - Пользователь должен иметь возможность выбрать язык программирования
  - Пользователь должен видеть в реальном времени код соперника
  - Пользователь должен иметь возможность выбрать сложность игры
  - Пользователь должен иметь возможность выбрать время игры
  - Пользователь должен иметь возможность выбора задачи
  - Пользователь должен иметь возможность выбора соперников
  - Пользователь должен иметь возможность просматривать информацию о своём
    профиле (рейтинг, статистика игр и т.д)
  - Пользователь должен иметь возможность просматривать общий рейтинг всех
    игроков
  - Пользователь должен иметь возможность просматривать историю игр, игры в
    записи
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован
    для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например,
    1000 одновременных пользователей)
implicit:
  - У пользователя должен быть личный кабинет, в котором отображается
    статистика, рейтинг
  - Пользователь должен иметь возможность вернуться в игру после вылета
  - Пользователь должен иметь возможность менять настройки игры (звук, никнейм)
