---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизоваться на сайте
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность присоединиться к игре
  - Пользователь должен иметь возможность выбрать язык программирования
  - Пользователь должен видеть в реальном времени код соперника
  - Пользователь должен иметь возможность выбрать сложность игры
  - Пользователь должен иметь возможность выбрать время игры
  - Пользователь должен иметь возможность выбора задачи
  - Пользователь должен иметь возможность выбора соперников
  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность просмотра игр других участников
  - Пользователь должен иметь возможность общаться в чате
  - Пользователь должен иметь возможность просмотра истории своих игр и других участников
  - Пользователь должен иметь возможность отмены созданной игры
  - Пользователь должен видеть свой рейтинг и рейтинг других игроков
  - Пользователь дожен видеть игроков online
